title: Akash Giri | Blog
description: > # this means to ignore newlines until "baseurl:"
  Hello, I am Akash Giri, welcome to my blog. I write about technical things here
  and some random stuff that I find useful.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://akashgiricse.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Akash Giri # add your name
author-img: mrrango.png # add your photo
about-author: I am a web developer focusing on back-end development. Always hungry to keep learning. # add description
social-twitter: akashgiricse # add your Twitter handle
social-githubpage: akashgiricse # add your root github page handle
social-github: akashgiricse # add your Github handle
social-linkedin: akashgiricse # add your Linkedin handle
social-email: akashgiricse@gmail.com # add your Email address

# Disqus
discus-identifier: akashgiricse # add your discus identifier

# Tracker
analytics: UA-121417321-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "yarn.lock"]
